portfolio_monthly_hard_limit_amount: 5500
assume_recommended_allocations_executed: true

tech_growth:
  asset_groups: [nasdaq100, hstech, global_tech]
  monthly_observe_amount: 2500
  monthly_warning_amount: 3000

sell_rules:
  enabled: false
  no_sell_before_non_dividend_total_amount: 10000
  excluded_asset_groups: [dividend_low_vol_50]
